# Generated by Django 2.1.2 on 2018-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voterslog',
            fields=[
                ('voterId', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('emailId', models.CharField(max_length=150)),
            ],
        ),
    ]
