# Generated by Django 2.1.2 on 2018-10-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersDet',
            fields=[
                ('City', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('phNo', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='voterslog',
            name='DoB',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='voterslog',
            name='voterId',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='votersdet',
            name='voterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evoting.Voterslog'),
        ),
    ]
