# Generated by Django 2.1.2 on 2018-11-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters_profile',
            name='activation',
        ),
        migrations.RemoveField(
            model_name='voters_profile',
            name='election',
        ),
        migrations.AlterField(
            model_name='voters_profile',
            name='region',
            field=models.CharField(choices=[(0, 'AndhraPradesh'), (1, 'Bihar'), (2, 'karnataka'), (3, 'Tamilnadu'), (4, 'Kerela'), (5, 'UttarPradesh'), (6, 'WestBengal'), (7, 'MadhyaPradesh'), (8, 'Haryana'), (9, 'Assam')], max_length=10),
        ),
    ]
