# Generated by Django 2.1.2 on 2018-11-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0002_auto_20181111_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_profile',
            name='activation',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
