# Generated by Django 2.1.2 on 2018-10-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0002_auto_20181019_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterslog',
            name='voterId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
