# Generated by Django 2.1.2 on 2018-11-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0002_auto_20181125_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters_profile',
            name='type',
            field=models.CharField(choices=[(0, 'Organiser'), (1, 'Voter')], default='', max_length=1),
        ),
    ]
