# Generated by Django 2.1.2 on 2018-11-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0003_voters_profile_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Registered_Database',
            fields=[
                ('voterId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(max_length=30)),
            ],
        ),
    ]
