# Generated by Django 2.1.2 on 2018-11-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0004_pre_registered_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_registered_database',
            name='fullname',
            field=models.CharField(max_length=50),
        ),
    ]
