# Generated by Django 2.1.2 on 2018-11-27 21:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('evoting', '0004_auto_20181127_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
            ],
            options={
                'ordering': ('email',),
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='voters_profile',
            name='region',
            field=models.CharField(choices=[('0', 'AndhraPradesh'), ('1', 'Bihar'), ('2', 'karnataka'), ('3', 'Tamilnadu'), ('4', 'Kerela'), ('5', 'UttarPradesh'), ('6', 'WestBengal'), ('7', 'MadhyaPradesh'), ('8', 'Haryana'), ('9', 'Assam')], max_length=10),
        ),
        migrations.AlterField(
            model_name='voters_profile',
            name='type',
            field=models.CharField(choices=[('0', 'Organiser'), ('1', 'Voter')], default=1, max_length=1),
        ),
    ]
