# Generated by Django 2.1.2 on 2018-11-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0005_auto_20181115_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_registered_database',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
