# Generated by Django 2.1.2 on 2018-11-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0005_auto_20181128_0320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
