# Generated by Django 2.1.2 on 2018-10-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evoting', '0005_auto_20181019_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voterslog',
            fields=[
                ('voterId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=150)),
                ('DoB', models.CharField(max_length=10)),
                ('emailId', models.EmailField(max_length=150)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
