# Generated by Django 2.1.2 on 2018-10-29 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evoting', '0006_voterslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterslog',
            name='emailId',
        ),
        migrations.RemoveField(
            model_name='voterslog',
            name='password',
        ),
        migrations.AddField(
            model_name='voterslog',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
