# Generated by Django 2.1.2 on 2018-10-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0007_auto_20181030_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterslog',
            name='user',
        ),
    ]
