# Generated by Django 2.1.2 on 2018-11-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0008_auto_20181116_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='voters_profile',
            name='voterId',
            field=models.BigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
