# Generated by Django 2.1.2 on 2018-10-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0008_remove_voterslog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voterslog',
        ),
    ]
