# Generated by Django 2.1.2 on 2018-10-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('evoting', '0009_delete_voterslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotersLog',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('voterId', models.BigIntegerField(default=0)),
                ('fullname', models.CharField(default='', max_length=20)),
                ('dob', models.DateField(default='')),
            ],
        ),
    ]
