# Generated by Django 2.1.2 on 2018-11-12 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_part', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterlog',
            name='fullname',
        ),
    ]
