# Generated by Django 2.1.2 on 2018-11-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_part', '0002_remove_voterlog_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterlog',
            name='fullname',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='candidatelog',
            name='candidate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidatelog',
            name='region_2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='voterlog',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='voterlog',
            name='region',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
