# Generated by Django 2.1.3 on 2018-11-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_fname', models.CharField(max_length=50)),
                ('candidate_party', models.CharField(choices=[('BJP', 'Bhartiya Janta Party'), ('INC', 'Indian National Congress'), ('SP', 'Samajwadi Party'), ('TDP', 'Telugu Desam Party'), ('AAP', 'Aam Aadmi Party'), ('JD', 'Janata Dal'), ('CPI', 'Communist Party of India'), ('TRS', 'Telangana Rashtra Samithi'), ('RJD', 'Rashtriya Janata Dal'), ('SS', 'Shiv Sena')], max_length=10)),
                ('candidate_region', models.CharField(choices=[(0, 'AndhraPradesh'), (1, 'Bihar'), (2, 'karnataka'), (3, 'Tamilnadu'), (4, 'Kerela'), (5, 'UttarPradesh'), (6, 'WestBengal'), (7, 'MadhyaPradesh'), (8, 'Haryana'), (9, 'Assam')], max_length=10)),
                ('candidate_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('candidate_email', models.EmailField(max_length=254, unique=True)),
                ('candidate_dob', models.DateField()),
                ('candidate_aadhar', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Election_region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[(0, 'AndhraPradesh'), (1, 'Bihar'), (2, 'karnataka'), (3, 'Tamilnadu'), (4, 'Kerela'), (5, 'UttarPradesh'), (6, 'WestBengal'), (7, 'MadhyaPradesh'), (8, 'Haryana'), (9, 'Assam')], max_length=10)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Vote_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organiser_app.Voter')),
            ],
        ),
    ]
