# Generated by Django 2.1.3 on 2018-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('INC', 'Indian National Congress'), ('RJD', 'Rashtriya Janata Dal'), ('TRS', 'Telangana Rashtra Samithi'), ('SP', 'Samajwadi Party'), ('SS', 'Shiv Sena'), ('AAP', 'Aam Aadmi Party'), ('CPI', 'Communist Party of India'), ('BJP', 'Bhartiya Janta Party'), ('JD', 'Janata Dal'), ('TDP', 'Telugu Desam Party')], max_length=10),
        ),
    ]
