# Generated by Django 2.1.3 on 2018-11-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0002_candidate_candidate_election_election_region_vote_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('RJD', 'Rashtriya Janata Dal'), ('JD', 'Janata Dal'), ('SS', 'Shiv Sena'), ('BJP', 'Bhartiya Janta Party'), ('AAP', 'Aam Aadmi Party'), ('SP', 'Samajwadi Party'), ('TDP', 'Telugu Desam Party'), ('CPI', 'Communist Party of India'), ('TRS', 'Telangana Rashtra Samithi'), ('INC', 'Indian National Congress')], max_length=10),
        ),
    ]
