# Generated by Django 2.1.2 on 2018-11-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0003_auto_20181117_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('CPI', 'Communist Party of India'), ('JD', 'Janata Dal'), ('TRS', 'Telangana Rashtra Samithi'), ('SP', 'Samajwadi Party'), ('AAP', 'Aam Aadmi Party'), ('TDP', 'Telugu Desam Party'), ('INC', 'Indian National Congress'), ('SS', 'Shiv Sena'), ('BJP', 'Bhartiya Janta Party'), ('RJD', 'Rashtriya Janata Dal')], max_length=10),
        ),
    ]
