# Generated by Django 2.1.3 on 2018-11-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0003_auto_20181117_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('TRS', 'Telangana Rashtra Samithi'), ('AAP', 'Aam Aadmi Party'), ('INC', 'Indian National Congress'), ('CPI', 'Communist Party of India'), ('TDP', 'Telugu Desam Party'), ('JD', 'Janata Dal'), ('BJP', 'Bhartiya Janta Party'), ('SS', 'Shiv Sena'), ('RJD', 'Rashtriya Janata Dal'), ('SP', 'Samajwadi Party')], max_length=10),
        ),
    ]
