# Generated by Django 2.1.2 on 2018-11-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0004_auto_20181118_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('TRS', 'Telangana Rashtra Samithi'), ('JD', 'Janata Dal'), ('TDP', 'Telugu Desam Party'), ('SP', 'Samajwadi Party'), ('CPI', 'Communist Party of India'), ('BJP', 'Bhartiya Janta Party'), ('INC', 'Indian National Congress'), ('RJD', 'Rashtriya Janata Dal'), ('AAP', 'Aam Aadmi Party'), ('SS', 'Shiv Sena')], max_length=10),
        ),
    ]
