# Generated by Django 2.1.3 on 2018-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0004_auto_20181117_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('TRS', 'Telangana Rashtra Samithi'), ('TDP', 'Telugu Desam Party'), ('SS', 'Shiv Sena'), ('SP', 'Samajwadi Party'), ('JD', 'Janata Dal'), ('INC', 'Indian National Congress'), ('CPI', 'Communist Party of India'), ('AAP', 'Aam Aadmi Party'), ('RJD', 'Rashtriya Janata Dal'), ('BJP', 'Bhartiya Janta Party')], max_length=10),
        ),
    ]
