# Generated by Django 2.1.3 on 2018-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organiser_app', '0005_auto_20181117_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_party',
            field=models.CharField(choices=[('AAP', 'Aam Aadmi Party'), ('TDP', 'Telugu Desam Party'), ('SS', 'Shiv Sena'), ('RJD', 'Rashtriya Janata Dal'), ('TRS', 'Telangana Rashtra Samithi'), ('SP', 'Samajwadi Party'), ('BJP', 'Bhartiya Janta Party'), ('INC', 'Indian National Congress'), ('CPI', 'Communist Party of India'), ('JD', 'Janata Dal')], max_length=10),
        ),
    ]
