# Generated by Django 2.1.3 on 2018-11-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidateLog',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_2', models.CharField(max_length=150, null='True')),
                ('candidate', models.CharField(max_length=50, null='True')),
                ('phone_no', models.BigIntegerField(null='true')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_birth', models.DateField(null='true')),
                ('party', models.CharField(max_length=50, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='voterLog',
            fields=[
                ('fullname', models.CharField(max_length=150, null='True')),
                ('email', models.CharField(max_length=150, null='True')),
                ('region', models.CharField(max_length=150, null='True')),
                ('voterid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
