# Generated by Django 2.0.5 on 2018-12-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('feedback', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=10, unique=True)),
                ('total', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Report_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('report', models.CharField(max_length=300)),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
