# Generated by Django 2.1.2 on 2018-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_auto_20181105_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gen',
            name='party',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
