# Generated by Django 2.1.2 on 2018-11-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='Report_data',
        ),
    ]
