# Generated by Django 2.1.2 on 2018-11-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0008_auto_20181121_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_data',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='report_data',
            name='name1',
            field=models.CharField(max_length=30),
        ),
    ]
