# Generated by Django 2.1.2 on 2018-12-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0009_auto_20181121_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
